apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pods
  name: pods
spec:
  containers:
  - args:
    - hello-k8s-sample
    image: nginx
    name: pods
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred3
