apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod-multi-pod
  name: test-pod-multi-pod
spec:
  containers:
  - image: nginx
    name: test-pod
    ports:
    - containerPort: 80
  - image: nginx
    name: test-pod-2
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: regcred3
